/** @type {import('tailwindcss').Config} */
module.exports = {
	darkMode: ['class'],
	content: [
		'./pages/**/*.{ts,tsx}',
		'./components/**/*.{ts,tsx}',
		'./app/**/*.{ts,tsx}',
		'./src/**/*.{ts,tsx}',
	],
	theme: {
		container: {
			center: true,
			padding: {
				DEFAULT: '1rem',
				sm: '1.5rem',
				md: '2rem',
				lg: '3rem',
				xl: '4rem',
				'2xl': '5rem',
			},
			screens: {
				xs: '320px',
				sm: '480px',
				'sm-plus': '640px',
				md: '768px',
				lg: '1024px',
				xl: '1280px',
				'2xl': '1400px',
				'ultra': '1440px',
			},
		},
		screens: {
			'xs': '320px',
			'sm': '480px',
			'sm-plus': '640px',
			'md': '768px',
			'lg': '1024px',
			'xl': '1280px',
			'2xl': '1400px',
			'ultra': '1440px',
		},
		extend: {
			colors: {
				// Workspace.ae Color Palette
				primary: {
					50: '#f8f9fa',
					100: '#e9ecef',
					200: '#dee2e6',
					300: '#ced4da',
					400: '#adb5bd',
					500: '#6c757d',
					600: '#495057',
					700: '#343a40',
					800: '#212529',
					900: '#000000',
					DEFAULT: '#000000',
				},
				accent: {
					blue: '#3B82F6',
					purple: '#6366F1',
					light: '#8B5CF6',
				},
				sale: {
					red: '#EF4444',
					orange: '#F97316',
					DEFAULT: '#EF4444',
				},
				neutral: {
					0: '#FFFFFF',
					50: '#F8F9FA',
					100: '#F1F3F4',
					200: '#E8EAED',
					300: '#DADCE0',
					400: '#BDC1C6',
					500: '#9AA0A6',
					600: '#80868B',
					700: '#5F6368',
					800: '#3C4043',
					900: '#202124',
				},
				background: {
					page: '#FFFFFF',
					section: '#F8F9FA',
					card: '#FFFFFF',
					overlay: 'rgba(0, 0, 0, 0.6)',
				},
				success: '#10B981',
				error: '#EF4444',
				warning: '#F59E0B',
				info: '#3B82F6',
			},
			fontFamily: {
				sans: ['Inter', 'system-ui', 'sans-serif'],
				heading: ['Inter', 'system-ui', 'sans-serif'],
				body: ['Inter', 'system-ui', 'sans-serif'],
			},
			fontSize: {
				xs: 'var(--text-xs)',
				sm: 'var(--text-sm)',
				base: 'var(--text-base)',
				lg: 'var(--text-lg)',
				xl: 'var(--text-xl)',
				'2xl': 'var(--text-2xl)',
				'3xl': 'var(--text-3xl)',
				'4xl': 'var(--text-4xl)',
				'5xl': 'var(--text-5xl)',
				'6xl': 'var(--text-6xl)',
			},
			spacing: {
				'0': 'var(--space-0)',
				'1': 'var(--space-1)',
				'2': 'var(--space-2)',
				'3': 'var(--space-3)',
				'4': 'var(--space-4)',
				'5': 'var(--space-5)',
				'6': 'var(--space-6)',
				'8': 'var(--space-8)',
				'10': 'var(--space-10)',
				'12': 'var(--space-12)',
				'16': 'var(--space-16)',
				'20': 'var(--space-20)',
				'24': 'var(--space-24)',
				'32': 'var(--space-32)',
			},
			borderRadius: {
				none: 'var(--radius-none)',
				sm: 'var(--radius-sm)',
				md: 'var(--radius-md)',
				lg: 'var(--radius-lg)',
				xl: 'var(--radius-xl)',
				'2xl': 'var(--radius-2xl)',
				full: 'var(--radius-full)',
			},
			boxShadow: {
				sm: 'var(--shadow-sm)',
				md: 'var(--shadow-md)',
				lg: 'var(--shadow-lg)',
				xl: 'var(--shadow-xl)',
				'2xl': 'var(--shadow-2xl)',
				card: '0 4px 12px rgba(0, 0, 0, 0.08)',
				'card-hover': '0 8px 24px rgba(0, 0, 0, 0.12)',
			},
			transitionDuration: {
				fast: 'var(--transition-fast)',
				normal: 'var(--transition-normal)',
				slow: 'var(--transition-slow)',
			},
			transitionTimingFunction: {
				smooth: 'cubic-bezier(0.4, 0, 0.2, 1)',
			},
			keyframes: {
				'fade-in': {
					'0%': { opacity: '0', transform: 'translateY(10px)' },
					'100%': { opacity: '1', transform: 'translateY(0)' },
				},
				'slide-up': {
					'0%': { transform: 'translateY(100%)' },
					'100%': { transform: 'translateY(0)' },
				},
				'slide-down': {
					'0%': { transform: 'translateY(-100%)' },
					'100%': { transform: 'translateY(0)' },
				},
			},
			animation: {
				'fade-in': 'fade-in 0.3s ease-out',
				'slide-up': 'slide-up 0.3s ease-out',
				'slide-down': 'slide-down 0.3s ease-out',
			},
		},
	},
	plugins: [require('tailwindcss-animate')],
}
