CREATE TABLE orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_number TEXT UNIQUE NOT NULL,
    quotation_id UUID,
    customer_id UUID NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending',
    'confirmed',
    'production',
    'shipped',
    'delivered',
    'cancelled')),
    payment_status TEXT DEFAULT 'pending' CHECK (payment_status IN ('pending',
    'partial',
    'paid',
    'refunded')),
    subtotal DECIMAL(12,2) NOT NULL,
    tax_amount DECIMAL(12,2) DEFAULT 0,
    discount_amount DECIMAL(12,2) DEFAULT 0,
    shipping_cost DECIMAL(12,2) DEFAULT 0,
    total_amount DECIMAL(12,2) NOT NULL,
    currency TEXT DEFAULT 'PKR',
    shipping_address JSONB,
    billing_address JSONB,
    payment_method TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);