CREATE TABLE products (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    sku TEXT UNIQUE NOT NULL,
    description TEXT,
    category_id UUID,
    base_price DECIMAL(12,2) NOT NULL,
    cost_price DECIMAL(12,2),
    dimensions JSONB,
    weight DECIMAL(10,2),
    materials JSONB,
    finishes JSONB,
    images JSONB,
    panorama_image TEXT,
    is_customizable BOOLEAN DEFAULT FALSE,
    is_featured BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    stock_status TEXT DEFAULT 'in_stock' CHECK (stock_status IN ('in_stock',
    'out_of_stock',
    'made_to_order')),
    metadata JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);